apiVersion: v1
kind: Service
metadata:
  name: civil-events-service
spec:
  selector:
    app: civil-events  # Must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: ClusterIP