apiVersion: apps/v1
kind: Deployment
metadata:
  name: civil-events-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: civil-events
  template:
    metadata:
      labels:
        app: civil-events
    spec:
      containers:
      - name: civil-events
        image: raoufrazi/civil-events-service:v1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/"
        - name: SPRING_DATASOURCE_USERNAME
          value: "****"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "****"  # Use quotes for special characters
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: "org.postgresql.Driver"
        - name: SPRING_JPA_HIBERNATE_DDL-AUTO
          value: "update"